apiVersion: v1
kind: Pod
metadata:
  name: prometheus-pod
  namespace: myproject01
  labels:
    app: prometheus
spec:
  containers:
    - name: prometheus
      image: prom/prometheus:v2.52.0
      ports:
        - containerPort: 9090