apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: {{ .Values.namespace }}  # This sets the namespace dynamically

spec:
  replicas: {{ .Values.client.replicas }}
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: {{ .Values.client.image }}
        ports:
        - containerPort: 80
