apiVersion: v1
kind: Pod
metadata:
  name: argocd-pod
  namespace: argocd
  labels:
    app: argocd
spec:
  containers:
    - name: argocd
      image: argoproj/argocd
      ports:
        - containerPort: 8080